### ISSUE TITLE
Support for communication channel (Slack/Email)

### ISSUE THREAD

**Issue by usamaahmadkhan** [openshift/pagerduty-operator#95]
**Purpose:**
A communication channel for a pagerduty service can send alerts to a specific email/slack channel that can help to track incidents for teams

**How:**
Add a `NOTIFY_EMAIL` or `SLACK_CHANNEL_URL` and `SLACK_CHANNEL_NAME` variables in the secret that can be watched and create communication channels for services in pagerduty.

**Comment by RiRa12621** [comment]
Hey @usamaahmadkhan,
thanks for the issue. We initially were only using this internally and followed the upstream first approach of making it available and open sourcing it.
I will label this as "feature" request, but not sure if we will be able to work on it.
With that being said, contributions are very welcome, in case you want to send a PR over

**Comment by ahmedwaleedmalik** [comment]
Hi @RiRa12621, we are going to work on adding support for configuring slack and jira service desk extensions for the pagerduty service that is created against a `ClusterDeployment`.
